"""
upload_longform.py
──────────────────
Uploads the long-form wildlife documentary to YouTube.
Regular video (not Shorts) with chapter timestamps in description.
"""

import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "pipeline"))

from pipeline.youtube_uploader import upload_short
from pipeline.trending_hashtags import get_trending_hashtags


def main():
    print("=" * 58)
    print("  WildStrikeAI — Long-Form Upload")
    print("=" * 58)

    # Load chapter timestamps generated by generate_longform.py
    chapters = ""
    if os.path.exists("longform_chapters.txt"):
        with open("longform_chapters.txt") as f:
            chapters = f.read().strip()

    # Fetch 7-10 trending hashtags for description
    print("\n[Trending] Fetching hashtags...")
    try:
        tags = get_trending_hashtags(youtube_api_key=os.environ["YOUTUBE_API_KEY"])
        trending = tags[:10]
    except Exception as e:
        print(f"[Trending] Failed: {e} — using base tags")
        trending = ["wildlife", "predator", "nature", "animals", "WildStrikeAI",
                    "NatureDocumentary", "lion", "cheetah", "shark"]

    hashtag_line = " ".join(f"#{t.lstrip('#')}" for t in trending)

    title = "Nature's Greatest Hunters: 5 Predators in Action 🦁 | WildStrikeAI"

    description = (
        "Five of nature's most powerful predators — one documentary.\n\n"
        "Real wildlife footage. Cinematic AI narration. No filler.\n\n"
        "New wildlife video every day. Subscribe and never miss a hunt.\n\n"
        "─── CHAPTERS ───\n"
        f"{chapters}\n\n"
        "─────────────────\n\n"
        f"{hashtag_line}\n"
        "#Wildlife #NatureDocumentary #WildStrikeAI #Animals #Predator #NatureFilm #Lion #Cheetah"
    )

    tags_list = [t.lstrip('#') for t in trending] + [
        "wildlife", "nature documentary", "predator", "animals",
        "WildStrikeAI", "lion", "cheetah", "crocodile", "wolf", "shark",
        "nature", "animal planet", "wildlife documentary",
    ]

    print(f"\n[Upload] Title: {title}")
    print(f"[Upload] Trending tags: {trending[:5]}...")

    print("\n[Upload] Uploading long-form video to YouTube...")
    try:
        upload_short(
            "final_longform.mp4",
            "longform_thumbnail.jpg",
            title=title,
            description=description,
            tags=tags_list[:30],
            mimetype="video/mp4",
        )
    except Exception as e:
        print(f"\n[FAILED] Video was NOT uploaded to YouTube.")
        print(f"[FAILED] Reason: {e}")
        print("=" * 58)
        sys.exit(1)

    print("\n" + "=" * 58)
    print("  Done! Check your YouTube channel.")
    print("=" * 58)


if __name__ == "__main__":
    main()
